### ISSUE TITLE
Need to install Autominy project on ROS noetic 

### ISSUE THREAD

**Issue by Dan61mx** [AutoMiny/AutoMiny#11]
HI we are a group of students that we are currently working and learning how to use the noetic distribution, and one of our team mates had an issue with the disk storage, now he wanted to reinstall it, but now he is not able to do it on the noetic distribution, could you please give us access to the prev version'? thanks a lot in advance

**Comment by sundermann** [comment]
The noetic distribution is still available as usual in the noetic branch.
