### ISSUE TITLE
Warning after compiling Autominy

### ISSUE THREAD

**Issue by lassuns** [AutoMiny/AutoMiny#17]
Hey, 

I followed the steps of installing Autominy on Ubuntu 22.4.2 exactly, 
 
but after I compile Autominy, I get warning that  libtbb.so.2  may conflict with libtbb.so.2:

Summary: 19 packages finished [1min 42s]

 3 packages had stderr output: lidar_pose_estimation road_marking_localization stereo_camera_pose_estimation

/usr/bin/ld: warning: libtbb.so.2, needed by /usr/lib/x86_64-linux-gnu/libopencv_core.so.4.5.4d, may conflict with libtbb.so.12

I have tried removing one of the packages, but when I installed Autominy again, both of packeges
 libtbb.so.2  and libtbb.so.2  got installed again automatically.
 
Is this an issue that should be fixed? or I should just ignore this warning?
Greetings, Daniel

**Comment by sundermann** [comment]
Hi, you can ignore the warning
