### ISSUE TITLE
`catkin build` fails in jsk_rviz_plugin:make on clean install

### ISSUE THREAD

**Issue by Nilshut** [AutoMiny/AutoMiny#6]
I am trying to setup autominy following the steps in the [installation guide](https://autominy.github.io/AutoMiny/docs/installation/). The catkin build command fails with the following error message:
```
error: invalid use of incomplete type ‘class Ogre::SceneManager’
     manual_ = manager->createManualObject();
                      ^~
In file included from /home/nils/Desktop/Masterarbeit_ROS/autominy/catkin_ws/src/jsk_rviz_plugin/src/camera_info_display.h:41:0,
                 from /home/nils/Desktop/Masterarbeit_ROS/autominy/catkin_ws/src/jsk_rviz_plugin/src/camera_info_display.cpp:37:
/opt/ros/melodic/include/rviz/display.h:50:7: note: forward declaration of ‘class Ogre::SceneManager’

```
Here is complete error message: [catkin_build_log.txt](https://github.com/AutoMiny/AutoMiny/files/4982374/catkin_build_log.txt)

**Comment by sundermann** [comment]
Probably wrong OS version. We support Ubuntu 18.04 only.

**Comment by Nilshut** [comment]
Thanks. The matter has resolved itself.
