### ISSUE TITLE
Wifi connection

### ISSUE THREAD

**Issue by CarlosUPQ** [AutoMiny/AutoMiny#7]
greetings
Due to the pandemic we are working from home, since the car is configured to start automatically, but it does not have my Wi-Fi network name or password, it does not connect to the internet.
I tried modifying the /etc/netplan/02-wireless.yaml file, but it doesn't work, I have no experience with ROS, and I have moderate experience with Ubuntu Linux.
I can connect manually using a USB wifi antenna to connect to the Internet, but roscore does not start correctly.
i guess wlan1 is my usb wifi antenna
If I do not use my USB WiFi antenna, the autominy does not detect any network so I cannot connect manually
What I can do?
I thank you in advance for your attention 

saludos
Debido a la pandemia estamos trabajando desde casa, ya que el auto está configurado para arrancar automáticamente, pero no tiene mi nombre de red Wi-Fi ni contraseña, no se conecta a internet.
Intenté modificar el archivo /etc/netplan/02-wireless.yaml, pero no funciona, no tengo experiencia con ROS y tengo una experiencia moderada con Ubuntu Linux.
Puedo conectarme manualmente usando una antena wifi USB para conectarme a Internet, pero roscore no se inicia correctamente.
supongo que wlan1 es mi antena wifi usb
Si no utilizo mi antena WiFi USB, el autominy no detecta ninguna red, por lo que no puedo conectarme manualmente
¿Qué puedo hacer?
Te agradezco de antemano tu atención

![wifiConexion](https://user-images.githubusercontent.com/76502589/113966300-75da7e80-97f4-11eb-91d0-fdf1612c52f0.jpg)
![intento](https://user-images.githubusercontent.com/76502589/113966462-c0f49180-97f4-11eb-9879-bfd6a06f8cd6.png)
![NoRedesWifi](https://user-images.githubusercontent.com/76502589/113966914-9525db80-97f5-11eb-9056-4bd3d9eece5c.png)

**Comment by sundermann** [comment]
Hi check ros-config.sh in the home directory and change the IP address there as well.

**Comment by CarlosUPQ** [comment]
> Hi check ros-config.sh in the home directory and change the IP address there as well.

hi, thanks for your answer

ros-config.sh have the same IP of wlan0 10.200.8.181

in the Start Guide ( https://autominy.github.io/AutoMiny/docs/network/ ) it mentions that it should be IP | 192.168.43.XXX, where XXX should be our autominy number (181)

if I connect manually to Wifi using a Wifi USB antenna I can ping ROS, but master is not connected, and my IP is asigned randomly because of the instruction dhcp4: true, so I do not know how to access my WiFi from the autostart

I think that if I connect manually, ROS master do not connect to the wifi

![pingRos](https://user-images.githubusercontent.com/76502589/114104137-eda9b700-988f-11eb-991f-b6ad8687eb33.png)

![DefaultWiFi](https://user-images.githubusercontent.com/76502589/114103997-b3d8b080-988f-11eb-9974-617cdb0299de.PNG)

![rosconfig](https://user-images.githubusercontent.com/76502589/114103778-52b0dd00-988f-11eb-84bd-5b9b35d45169.png)

**Comment by sundermann** [comment]
You can try to disable dhcp and assign your ip address manually. The part with 192.168.43.XXX is only valid for the configurations we provided but in theory you should be able to choose any ip adress.

**Comment by CarlosUPQ** [comment]
> You can try to disable dhcp and assign your ip address manually. The part with 192.168.43.XXX is only valid for the configurations we provided but in theory you should be able to choose any ip adress.

thanks for your help, I didn't understand that I had to change "ROS" and "elfmeter" in 02-wireless.yaml file. I did it and put my own access point and password, now master is running
next I will try to connect via SSH from another device

![RosnodeList](https://user-images.githubusercontent.com/76502589/114127752-77717880-98c0-11eb-8846-3c8cc8132b04.png)
