### ISSUE TITLE
how to stop the auto start?

### ISSUE THREAD

**Issue by CarlosQroUPQ** [AutoMiny/AutoMiny#8]
hi from Querétaro México

I am learning to use the autominy, I can already connect using SSH from an application on my cell phone. To do this I had to change the IP configuration of the miny, allow inbound and outbound communication from the miny, disable the miny's firewall and configure my router to allow it to work with fixed IPs. 

![rosnode list](https://user-images.githubusercontent.com/83608937/116919952-a9ec6800-ac17-11eb-9650-17b43d36cd7b.jpeg)

Now some nodes respond to the echo instruction, but when trying to start the navigation it marks the errors in the image.

![nodo voltaje](https://user-images.githubusercontent.com/83608937/116919961-aeb11c00-ac17-11eb-9784-9f8e8c91402b.jpeg)

![error](https://user-images.githubusercontent.com/83608937/116919968-b1137600-ac17-11eb-9c57-5c81336c68be.jpeg)

 I would like to disable auto start to be able to work with different workspaces and learn to work with each node separately before trying to navigate. what should i do next?

thanks in advance

**Comment by sundermann** [comment]
Try `sudo systemctl disable autominy`

**Comment by CarlosQroUPQ** [comment]
Thanks, I will try each node at once to learn how it works
